//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class eventpost
    {
        public int event_id { get; set; }
        public string event_title { get; set; }
        public string event_description { get; set; }
        public Nullable<System.DateTime> event_startdate { get; set; }
        public Nullable<System.DateTime> event_enddate { get; set; }
        public string event_document_id { get; set; }
        public string event_gpslocation_id { get; set; }
        public string event_venue { get; set; }
        public Nullable<int> event_user_type { get; set; }
        public int user_id { get; set; }
    }
}
