//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class examschedule
    {
        public int examsec_id { get; set; }
        public Nullable<int> erm_id { get; set; }
        public int subject_id { get; set; }
        public string subject_name { get; set; }
        public System.DateTime exam_date { get; set; }
        public string exam_term { get; set; }
    }
}
