//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class examreportmapping
    {
        public int erm_id { get; set; }
        public Nullable<int> erm_section_id { get; set; }
        public Nullable<int> erm_class_id { get; set; }
        public int erm_institution_id { get; set; }
        public string exam_term { get; set; }
    }
}
