//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class gpslocation
    {
        public int gpslocation_id { get; set; }
        public string gpslocation_discription { get; set; }
        public string gpslocation_name { get; set; }
        public string gpslocation_location { get; set; }
        public int user_id { get; set; }
    }
}
