//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class group
    {
        public group()
        {
            this.usergroups = new HashSet<usergroup>();
        }
    
        public int group_id { get; set; }
        public string group_name { get; set; }
        public bool group_isactive { get; set; }
        public string group_description { get; set; }
        public Nullable<int> group_privacy { get; set; }
        public int user_id { get; set; }
    
        public virtual ICollection<usergroup> usergroups { get; set; }
        public virtual userinfo userinfo { get; set; }
    }
}
