//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class homeworkupload
    {
        public int homeworkupload_id { get; set; }
        public int homework_id { get; set; }
        public int hw_student_id { get; set; }
        public string hw_url { get; set; }
        public Nullable<bool> isactive { get; set; }
    }
}
