//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class homework
    {
        public int homework_id { get; set; }
        public int hw_institution_id { get; set; }
        public Nullable<int> hw_section_id { get; set; }
        public Nullable<int> hw_class_id { get; set; }
        public Nullable<int> hw_teacher_id { get; set; }
        public int hw_subject_id { get; set; }
        public string hw_description { get; set; }
        public System.DateTime hw_date { get; set; }
        public Nullable<bool> isactive { get; set; }
    }
}
