//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class instclssectionmapping
    {
        public int instclssection_id { get; set; }
        public int institution_id { get; set; }
        public int class_id { get; set; }
        public int section_id { get; set; }
        public Nullable<int> instclssection_strength { get; set; }
        public Nullable<int> instclssection_teacher_id { get; set; }
    }
}
