//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class parent
    {
        public int parent_id { get; set; }
        public int user_id { get; set; }
        public string parent_childeren { get; set; }
        public string parent_occupation { get; set; }
        public string parent_nameofspouse { get; set; }
    
        public virtual userinfo userinfo { get; set; }
    }
}
