//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class post
    {
        public int post_id { get; set; }
        public int user_id { get; set; }
        public string post_doc_id { get; set; }
        public string post_gpslocation_id { get; set; }
        public Nullable<System.DateTime> post_date { get; set; }
        public Nullable<int> post_user_type { get; set; }
        public string post_feeds { get; set; }
        public string post_tag_user_id { get; set; }
        public string post_event_id { get; set; }
    }
}
