//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class reportcard
    {
        public int recard_id { get; set; }
        public int erm_id { get; set; }
        public int student_id { get; set; }
        public int marks { get; set; }
        public string grade { get; set; }
        public string erm_term { get; set; }
        public int subject_id { get; set; }
    }
}
