//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class requeststatu
    {
        public int requeststatus_id { get; set; }
        public int request_from { get; set; }
        public int request_to { get; set; }
        public short request_status { get; set; }
        public int request_for_group { get; set; }
        public string request_note { get; set; }
        public System.DateTime request_crdate { get; set; }
        public Nullable<System.DateTime> request_upddate { get; set; }
    }
}
