//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public int student_id { get; set; }
        public int user_id { get; set; }
        public string student_father_name { get; set; }
        public string student_mother_name { get; set; }
        public string student_regid { get; set; }
        public int student_roll_no { get; set; }
        public Nullable<int> student_section { get; set; }
        public int student_class { get; set; }
        public int student_institution_id { get; set; }
        public string student_cca { get; set; }
        public string student_eca { get; set; }
    
        public virtual @class @class { get; set; }
        public virtual userinfo userinfo { get; set; }
        public virtual institution institution { get; set; }
    }
}
