//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class teacher
    {
        public int teacher_id { get; set; }
        public int user_id { get; set; }
        public string teacher_code { get; set; }
        public Nullable<int> teacher_institution_id { get; set; }
    
        public virtual userpersonalinfo userpersonalinfo { get; set; }
    }
}
