//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class timetable
    {
        public int timetable_id { get; set; }
        public Nullable<int> class_id { get; set; }
        public Nullable<int> section_id { get; set; }
        public int institution_id { get; set; }
        public Nullable<bool> isactive { get; set; }
        public string createdby { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
    }
}
