//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class userpersonalinfo
    {
        public userpersonalinfo()
        {
            this.teachers = new HashSet<teacher>();
        }
    
        public int userper_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<System.DateTime> userper_dob { get; set; }
        public Nullable<int> userper_gender { get; set; }
        public Nullable<int> userper_countryid { get; set; }
        public Nullable<int> userper_stateid { get; set; }
        public Nullable<int> userper_cityid { get; set; }
        public string userper_favoiritesubjects { get; set; }
        public string userper_sports { get; set; }
        public string userper_hobbies { get; set; }
        public string userper_personalities { get; set; }
        public string userper_books { get; set; }
        public string userper_movies { get; set; }
        public string userper_mobile { get; set; }
        public string userper_alternatemobile { get; set; }
        public string userper_profile_pic { get; set; }
    
        public virtual ICollection<teacher> teachers { get; set; }
    }
}
