//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class userinfo
    {
        public userinfo()
        {
            this.groups = new HashSet<group>();
            this.parents = new HashSet<parent>();
            this.students = new HashSet<student>();
        }
    
        public int user_id { get; set; }
        public string user_name { get; set; }
        public string user_email { get; set; }
        public string user_password { get; set; }
        public Nullable<bool> user_isactive { get; set; }
        public Nullable<bool> user_locked { get; set; }
        public Nullable<int> user_failedattempt { get; set; }
        public Nullable<System.DateTime> user_lockedtilldate { get; set; }
        public Nullable<int> user_type { get; set; }
        public Nullable<System.DateTime> user_crdate { get; set; }
        public Nullable<int> user_crby { get; set; }
        public Nullable<System.DateTime> user_upddate { get; set; }
        public Nullable<int> user_updby { get; set; }
        public string user_alternatemail { get; set; }
        public string pwdchange_oldpwd { get; set; }
        public string pwdchange_newpwd { get; set; }
        public Nullable<System.DateTime> pwdchange_redate { get; set; }
        public Nullable<System.DateTime> pwdchange_upddate { get; set; }
        public string pwdchange_guid { get; set; }
    
        public virtual ICollection<group> groups { get; set; }
        public virtual ICollection<parent> parents { get; set; }
        public virtual ICollection<student> students { get; set; }
    }
}
